# Generated by Django 4.1.11 on 2023-09-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoApp', '0002_carouselimage_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='news_images/')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
