# Generated by Django 4.1.11 on 2023-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoApp', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='authors/')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('full_text', models.TextField()),
                ('category', models.CharField(choices=[('ALL', 'All'), ('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('BIOLOGY', 'Biology')], default='ALL', max_length=10)),
                ('author_images', models.ManyToManyField(to='texnoApp.authorimage')),
            ],
        ),
    ]
