# Generated by Django 4.1.11 on 2023-09-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoApp', '0005_projectimage_rename_full_text_project_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Fotoğraf')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Fotoğraf Alt Metni')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Açıklama yok', verbose_name='Küçük Açıklama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('all', 'ALL'), ('software', 'Software'), ('hardware', 'Hardware'), ('biology', 'Biology')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Baslik yok', max_length=200, verbose_name='Başlık'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='texnoApp.image', verbose_name='Fotoğraflar'),
        ),
    ]
