# Generated by Django 4.1.11 on 2023-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoApp', '0006_image_remove_project_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('biology', 'Biology')], default='software', max_length=50),
        ),
    ]
