# Generated by Django 4.1.11 on 2023-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoApp', '0007_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='project_image', to='texnoApp.image', verbose_name='Fotoğraflar'),
        ),
    ]
