# Generated by Django 4.1.11 on 2023-09-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoApp', '0008_alter_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='projects',
            field=models.ManyToManyField(related_name='project_image', to='texnoApp.project', verbose_name='Fotoğraflar'),
        ),
    ]
