# Generated by Django 4.1.11 on 2023-09-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoApp', '0009_remove_project_images_image_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_text', models.TextField()),
                ('image', models.ImageField(upload_to='startups/')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
    ]
